### ISSUE TITLE
yiiActiveForm jQuery plugin don't trigger event "afterValidate" if not submitting 

### ISSUE THREAD

**Issue by agarb7** [yiisoft/yii2#10549]
In yiiActiveForm.js:

``` js
    var updateInputs = function ($form, messages, submitting) {
        /* ... */
        if (submitting) {
            /* ... */
            $form.trigger(events.afterValidate, [messages, errorAttributes]);
            /* ... */
        } 
        /* ... */
    };
```

And it is only "afterValidate" trigger for whole plugin.

**Comment by samdark** [comment]
How to reproduce it?

**Comment by agarb7** [comment]
Bug reproduced by this code
```js
$form.one('afterValidate', function() {                        
    console.log('afterValidate');
});

$form.yiiActiveForm('validate');
```

**Comment by samdark** [comment]
You mean `on`, not `one`, right?

**Comment by agarb7** [comment]
@samdark `.on()` or `.one()` in this case it does not matter. Anyway message must be printed, I think.
In project I used `.one()`, because after requested validation of first form it is need to show modal with another one. The first form isn't submitting, just used for validating (because I think it is simplest way for using validation functional of framework in this case)

**Comment by samdark** [comment]
It does matter. `.on()` binds a callback to event while `.one()` is getting first element in jQuery object.

**Comment by agarb7** [comment]
@samdark I used it according documentation http://api.jquery.com/one/ and it work fine for `afterValidateAttribute` event of `yiiActiveForm`.

**Comment by samdark** [comment]
Oh, I wasn't aware that it could be used in this way.

**Comment by lynicidn** [comment]
вот этот if (submiting) глючит с аякс валидацией, вот пр на бефоре валидейт https://github.com/yiisoft/yii2/pull/11743
там аналогичный баг

**Comment by DmLapin** [comment]
@samdark also pay attention to internals of [validate method](https://github.com/yiisoft/yii2/blob/2.0.8/framework/assets/yii.activeForm.js#L307-L308), please. In case of `$form.yiiActiveForm('validate')` manual call, no validation is performed. Simple extended way to check:
```
$form.on('beforeValidateAttribute afterValidate', function(event) {
    console.log(event);
});
$form.yiiActiveForm('validate');
```
`validate()` method has bad workflow: it depends on incomprehensible internal states of form and fields. It's really hard to understand meaning of `if (data.submitting || this.status === 2 || this.status === 3)`.

**Comment by samdark** [comment]
Yeah. Any ideas how to make it better?

**Comment by DmLapin** [comment]
There are few potential places for changes, but it can break compatibility (may be it could be included in 2.1 milestone):
- validate() should validate [regardless](https://github.com/yiisoft/yii2/blob/2.0.8/framework/assets/yii.activeForm.js#L308) of field.state or form.submitting and trigger appropriate events like before/afterValidate
- updateInputs() should work only with error messages, as it's doc [says](https://github.com/yiisoft/yii2/blob/2.0.8/framework/assets/yii.activeForm.js#L546) and should not [watch for internal form state](https://github.com/yiisoft/yii2/blob/2.0.8/framework/assets/yii.activeForm.js#L554) and should not [submit form by self](https://github.com/yiisoft/yii2/blob/2.0.8/framework/assets/yii.activeForm.js#L584).
- my logic tells me that validate() method should call validateAttribute() during its operation but not [vice versa](https://github.com/yiisoft/yii2/blob/2.0.8/framework/assets/yii.activeForm.js#L528).
- replace status = 1 / 2 / 3 (if activeForm really needs it) with comprehensible variables like STATUS_VALIDATED / STATUS_WAIT_FOR_VALIDATION / ...

But at current moment at least `validate()` and `updateInputs()` methods should be fixed to perform validation properly and trigger `afterValidate` event in case of manual call.

**Comment by samdark** [comment]
Fixed by https://github.com/yiisoft/yii2/commit/e8bcb93507a7859f2a5115ec2179182353e9cc04

**Comment by SamMousa** [comment]
This is not fixed; `afterValidate` is still not called after calling `validate()`.

It is only called by `updateInputs` and only when it is a validation triggered by form submission

**Comment by SilverFire** [comment]
According to the docs, `afterValidate event is triggered after validating the whole form`

By default, `validate` method call validates only fields that are not validated yet. In case you want to get `afterValidate` event, you need to validate the whole form by passing second argument:

```js
$form.yiiActiveForm('validate', true);
```

**Comment by SilverFire** [comment]
Moved @DmLapin suggestions to a separate issue #14957
