### ISSUE TITLE
Intl extension + Formatter + PHP7 = IntlException.

### ISSUE THREAD

**Issue by decimoseptimo** [yiisoft/yii2#11661]
I'm developing an application in yii 2.0.6 in an other than english language. Yii core messsages were translated correctly but I noticed dates weren't being formatted accordingly `/yii::$app->formatter->asDatetime($model->created_at);`. As per documentation I uncommented ;extension=php_intl.dll in php.ini file. Immediatly afterwards, I'm getting `IntlException  Constructor failed`. Migrated to yii 2.0.8 with no difference. Commenting back Intl extension reverts the issue.
 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7.0.*
| Operating system | XAMMP-win

**Comment by rob006** [comment]
duplicate #11528

**Comment by xiaoliushifu** [comment]
right,I also get that error from yii2. I try it directly in php:

$a = new IntlDateFormatter('zh-CN', -1, -1, 'Asia/ShangHai');
it still  error: IntlException: Constructor failed

**Comment by samdark** [comment]
Which version do you have it was fixed long time ago...

**Comment by xiaoliushifu** [comment]
This is Yii version 2.0.9.
php version is 7.0.10
OS is win7_64


application enviroment is WampServer Version 3.0.6 64bit
It still have that error.
I just change other way to directly use php's date  internel method ,avoiding that IntlDateFormatter libs.
for an example:
date（“y-m-d”,$timestamp）;

**Comment by samdark** [comment]
Well, you need to update. Current Yii version is 2.0.12.
