### ISSUE TITLE
Undesired behavior using AssetManager->publish

### ISSUE THREAD

**Issue by alex20465** [yiisoft/yii2#13152]
### What steps will reproduce the problem?
Try to publish a  file with dependencies using the mock assetManager of codeception.

Check this datetimepicker extension: https://github.com/nkovacs/yii2-datetimepicker/blob/master/DateTimePicker.php#L191

### What is the expected result?
The publishFile/Directory should copy and publish the bundles to the right place.

SUGGESTION: The mockAssetManager should be initialized and parse the aliases of the basePath attribute. Even if the assetManager is disabled and mocked the publish methods should work properly.

### What do you get instead?
Asset manager publishes the asset to the wrong folder without parsing the basePath, which contains mostly the alias '@webroot'. The results is a new folder under the project-root: './@webroot/assets/..'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | PHP 5.6.23
| Operating system | Linux xxxxx 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by samdark** [comment]
I think it's already fixed in Codeception master. Anyway, it is not an issue of Yii core framework.

**Comment by alex20465** [comment]
Yes you have right, `\Codeception\Lib\Connector\Yii2` is responsible to mock the assetManager.

But the issue with the `@webroot` directory still exists when you use the `publish()` method. (https://github.com/Codeception/Codeception/issues/3706)

but thanks anyway.
