### ISSUE TITLE
Why still using deprecated jQuery(document).ready()?

### ISSUE THREAD

**Issue by alexantr** [yiisoft/yii2#14620]
`yii\web\View` uses not recommended way to include scripts in POS_READY section.

jQuery recommends to use
```js
jQuery(function () { /* code */ });
```
instead
```js
jQuery(document).ready(function () { /* code */ });
```

Also see in [jQuery docs](https://api.jquery.com/ready/):

> There is also `$(document).on( "ready", handler )`, *deprecated as of jQuery 1.8 and removed in jQuery 3.0*. Note that if the DOM becomes ready before this event is attached, the handler *will not be executed*.

One more thing. You can pass jQuery object to handler with `$`:
```js
jQuery(function ($) {
    // using $ here will be safely even jQuery.noConflict() will be enabled
});
```

And one more thing. To use `$` safely in POS_LOAD section construction `jQuery(window).on('load', function () { });` can be placed into `jQuery(function ($) { });`:

```js
jQuery(function ($) {
    $(window).on('load', function () {
        // POS_LOAD scripts. Can use $
    });
    // POS_READY scripts
});
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.*
| PHP version      | 5.4-7.x
| Operating system | all

**Comment by klimov-paul** [comment]
Relates #13839

**Comment by SilverFire** [comment]
Related to #14338

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/3a8feb17a8213362d79bfbb32dc89621c1de42f1

**Comment by klimov-paul** [comment]
Complete removal of the `JQuery.ready()` looks pretty odd: this method still exists at jQuery library and I do not see any note about its been deprecated.
Would not its usage removal break particular JS code?

**Comment by alexantr** [comment]
My mistake. Only `.on("ready", handler)` deprecated and removed in 3.0, not `.ready(handler)`. 
But anyway short syntax `$(handler)` is equivalent:
> jQuery offers several ways to attach a function that will run when the DOM is ready. All of the following syntaxes are equivalent:
> `$( handler )`
> `$( document ).ready( handler )`
> `$( "document" ).ready( handler )`
> `$( "img" ).ready( handler )`
> `$().ready( handler )`

**Comment by gpcaretti** [comment]
@alexantr 
> My mistake. Only .on("ready", handler) deprecated and removed in 3.0, 
> not .ready(handler). But anyway short syntax $(handler) is equivalent:
> $( handler )
>$( document ).ready( handler )

This is not correct.  The jquery document continues [(see here)](https://api.jquery.com/ready/): 
"As of jQuery 3.0, only the first syntax is recommended; the other syntaxes still work but are deprecated."

**Comment by Shashimii** [comment]
This issue helped me understanding jquery syntax 👍
