### ISSUE TITLE
Oracle DbSession problem

### ISSUE THREAD

**Issue by sheillendra** [yiisoft/yii2#15708]
After update yii2 to 2.0.14 version, I get error : 

https://pastebin.com/2H0AquHH

In 2.0.13 version is running well.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1
| Operating system | Centos 7
| Oracle Version | 12.2

**Comment by samdark** [comment]
@sergeymakinen looks like upsert issue to me, is it?

**Comment by sergeymakinen** [comment]
Yes, I suspect it’s about upsert.

**Comment by SilverFire** [comment]
See PR https://github.com/yiisoft/yii2/pull/15762

@sheillendra could you check, whether the Pull Request fixes the problem?

**Comment by SilverFire** [comment]
Fixed by #15764

**Comment by sheillendra** [comment]
@SilverFire error still occurs in version 2.0.14.2 hotfix. 

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1465 [Oracle][ODBC][Ora]ORA-01465: invalid hex number
 (SQLExecute[1465] at /builddir/build/BUILD/php-7.1.14/ext/pdo_odbc/odbc_stmt.c:260)
The SQL being executed was: MERGE INTO "prod_session" USING (SELECT '__flash|a:0:{}' AS "data", '2198f890f89f49d973d615af0c0c26d3' AS "id", 1520992947 AS "expire" FROM "DUAL") "EXCLUDED" ON ("prod_session"."id"="EXCLUDED"."id") WHEN MATCHED THEN UPDATE SET "data"="EXCLUDED"."data", "expire"="EXCLUDED"."expire" WHEN NOT MATCHED THEN INSERT ("data", "id", "expire") VALUES ("EXCLUDED"."data", "EXCLUDED"."id", "EXCLUDED"."expire") in /home/ec2-user/html/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/ec2-user/html/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'MERGE INTO "pro...')
#1 /home/ec2-user/html/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('MERGE INTO "pro...')
#2 /home/ec2-user/html/vendor/yiisoft/yii2/web/DbSession.php(174): yii\db\Command->execute()
#3 [internal function]: yii\web\DbSession->writeSession('2198f890f89f49d...', '__flash|a:0:{}')
#4 /home/ec2-user/html/vendor/yiisoft/yii2/web/Session.php(302): session_regenerate_id(false)
#5 /home/ec2-user/html/vendor/yiisoft/yii2/web/DbSession.php(105): yii\web\Session->regenerateID(false)
#6 /home/ec2-user/html/vendor/yiisoft/yii2/web/User.php(651): yii\web\DbSession->regenerateID(true)
#7 /home/ec2-user/html/vendor/yiisoft/yii2/web/User.php(252): yii\web\User->switchIdentity(Object(common\models\UserCrud), 2592000)
#8 /home/ec2-user/html/backend/models/LoginForm.php(64): yii\web\User->login(Object(common\models\UserCrud), 2592000)
#9 /home/ec2-user/html/backend/controllers/SiteController.php(76): backend\models\LoginForm->login('admingroup')
#10 [internal function]: backend\controllers\SiteController->actionLogin()
#11 /home/ec2-user/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/ec2-user/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)

**Comment by SilverFire** [comment]
What is the expected SQL?

**Comment by SilverFire** [comment]
// Open a new issue, please
