### ISSUE TITLE
Array field in PostgreSQL return 0

### ISSUE THREAD

**Issue by Commander223** [yiisoft/yii2#15854]
### What steps will reproduce the problem?
Create PostgreSQL table with array field
`arrayFiels integer[]`
disable array support
`'disableArraySupport' => true`
insert some data to db
`{1, 2, 3}`
### What is the expected result?
Model return string which I transform to array
```
TestModel {
    arrayFiels => '{1, 2, 3}'
}
```
### What do you get instead?
```
TestModel {
    arrayFiels => 0
}
```
### Additional info
yii2/db/ColumnSchema::phpTypecast return integer for array type fields, that why array converted to 0
string to int
`(ind)'{1, 2, 3}'`
Also that effect to gii, create model
`[['arrayFiels'], 'integer']`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.1.14
| Operating system | Ubuntu 16.04.4

**Comment by SilverFire** [comment]
Fixed by #15855

**Comment by Commander223** [comment]
Thx, but not fully fixed, 
`yii2/db/ColumnSchema::phpTypecast`
still return integer for array, gii use this method for creating models, so when we generate models we have
`[['arrayFiels'], 'integer']`
but it should be
`[['arrayFiels'], 'string']`

**Comment by SilverFire** [comment]
Create a separate issue, please.
