### ISSUE TITLE
2.0.16 breaks certain select2 fields validation in active form

### ISSUE THREAD

**Issue by licanulla** [yiisoft/yii2#17147]
Just found that since upgrade 2.0.16 my select2 fields with ajax option are no longer validated. Those with preset data still are. No JS errors in console. Downgraded to 2.0.15.1 and got my forms working again.

**Comment by rob006** [comment]
Probably duplicate of https://github.com/yiisoft/yii2/issues/17111

How do you generate AJAX response for select2 widget?

**Comment by licanulla** [comment]
No AJAX calls in my case. The client-side validation is broken somehow so when the form is loaded and you hit "submit" button, those select2 fields (with `ajax` option) left empty aren't marked as required, while they are and the form is initialized with those fields are required.

**Comment by rob006** [comment]
You need to give some code to reproduce this issue.

**Comment by hooman-pro** [comment]
Issue moved to [yiisoft/db #59](https://github.com/yiisoft/db/issues/59) via [**ZenHub**](https://www.zenhub.com/)

**Comment by samdark** [comment]
Closing since there's no way to reproduce it without information on how.

**Comment by licanulla** [comment]
I'm now away from my laptop for 2 weeks, but the code is quite simple:
BS ActiveForm widget, inside it a select2 field with ajax option (remote data) and AR respective property rule is set to required. If you're able to reproduce the issue, I'll post the code here later.

**Comment by samdark** [comment]
select2 isn't part of the framework so it could be added in numerous ways.

**Comment by licanulla** [comment]
Understand that, but no matter which way it's added, the update breaks the validation of that particular field type in active form, which is a part of the framework. The reverse put things back to normal. Had no issues since the start at v2.0.6. I'll post the code to reproduce when back in mid March.

**Comment by samdark** [comment]
Deal. We'll re-open issue then.

**Comment by tmendesilva** [comment]
Same problem. I have several select2 input fields on my project and since 2.0.16 framework update validation **is not working only for virtual attributes**, attributes with database column validation is ok.

**Comment by samdark** [comment]
@tmendesilva would you please provide a way to reproduce the issue?

**Comment by tmendesilva** [comment]
Model:

```
class MyModel extends \yii\db\ActiveRecord {
    public $virtualAttr;
    public function rules() {
        return [
            [
                ['virtualAttr'], 'required'
            ],
        ];
    }
}
```
View:
```

$form = ActiveForm::begin([
       'validationUrl' => $validationUrl,
       'enableAjaxValidation' => true,
 ]);
      echo $form->field($model, 'virtualAttr')->widget(kartik\select2\Select2::class, []);
ActiveForm::end();
```

**Comment by licanulla** [comment]
It didn't work with database column attributes either. At least for me.
Select2 from kartik-v too. I moved to another project on Laravel but would appreciate if this bug is fixed.

**Comment by marianabm** [comment]
I think that the problem is that when select2 uses ajax there is no option element on select element. So, the validation is not working because of this piece of code on validate function (yii.activeForm.js)

```

if ($input.length && $input[0].tagName.toLowerCase() === 'select') {
    if (!$input[0].options.length) {
        return true;
    } else if (($input[0].options.length === 1) && ($input[0].options[0].value === '')) {
        return true;
    }
}
```

**Comment by devaptas** [comment]
Same problem here, no validation when select2 is empty (populates on search by AJAX request). After search and options populated, validation works even by removing select2.

**Comment by HenryVolkmer** [comment]
not a issue of yii, but a issue of kartik-v/select2.
A HTML5 `<select>` which is `required` MUST have at least one `<option>` Element.

> A select element with a required attribute and without a multiple attribute, and whose size is “1”, must have a child option element. 

https://w3c.github.io/html-reference/select.html

i open a PR @kartik-v /select2

**Comment by HenryVolkmer** [comment]
fixed with PR https://github.com/kartik-v/yii2-widget-select2/pull/298

**Comment by samdark** [comment]
Thanks for checking, @HenryVolkmer.

**Comment by licanulla** [comment]
Thanks, @HenryVolkmer !

**Comment by licanulla** [comment]
The fix does not help, unfortunately. At least in my project.

After updating kartik-v/yii2-widget-select2 to v2.1.5 (that includes the proposed fix) and yii2 to the most recent version (2.0.29), I have select2 fields initially having empty values as selected (instead of placeholders as it's supposed to be) and still, no validation working, if I clear the selection.

So reverting back to yii2-widget-select2 to v2.1.4 and yii 2.0.15.1 fixes the problem. We are again where we were.

**Comment by kartik-v** [comment]
This has been fixed with [this commit](https://github.com/kartik-v/yii2-widget-select2/commit/6a1a5e4bc80fff9c3341e1d9b718051db646031a)

**Comment by licanulla** [comment]
So with no changes made to my code and 
- latest yii2-widget-select2 (v2.1.7)
- latest yii (2.0.30)

the active form select2 fields validation is still broken. 
Reverting yii back to 2.015.1 fixes the issue.

Here is the snippet of how the field is created in the form:

>                 
            echo $form
                    ->field($model, 'customer_id')
                    ->widget(Select2::class, [
                        'data' => $data,
                        'theme' => Select2::THEME_BOOTSTRAP,
                        'options' => [
                            'readonly' => !!$source,
                            'placeholder' => ['id' => -1, 'text' => 'Select company'],
                        ],
                        'pluginOptions' => [
                            'width' => '100%',
                            'allowClear' => true,
                            'minimumInputLength' => 3,
                            'ajax' => [
                                'url' => Url::to(['/customer/list']),
                                'delay' => 250,
                                'dataType' => 'json',
                                'data' => new JsExpression('function(params) { return {q:params.term, page:params.page||1}; }')
                            ],
                        ],
                    ]);

It's a required field for the model and it's marked as so if submitted empty with yii 2.0.15.1:
![image](https://user-images.githubusercontent.com/10324311/69899997-6f213900-136e-11ea-9fd9-a86de01daf1f.png)
and it passes validation on yii >= 2.0.16 which is wrong.

Maybe I'm missing something 'cause the code is quite old and may be configuration array must be updated. But this is the actual case as described.

**Comment by Androphin** [comment]
@licanulla You have the same problem with AJAX and the Select2 widget as we do here https://github.com/kartik-v/yii2-widget-select2/pull/298#issuecomment-557086607.
There is something broken with yii.activeForm.js and how the selectbox creates option elements that aren't validated.

**Comment by licanulla** [comment]
@Androphin Yes, it's caused by the changes in yii.activeForm.js and still not fixed. 
Here is the comment from kartik-v: https://github.com/kartik-v/yii2-widget-select2/issues/289#issuecomment-567160614

Previously the code worked as expected: required select2 did not pass the validation is the model fields is set as required. I do not think having _an extra option beyond the empty one_ is a good solution though.

**Comment by buttflattery** [comment]
i second it, the validation does not work with a select2 with ajax, the validation is skipped for the required fields even using the `whenClient` option. unless you provide a default option like 

```
Select2::class,
            [
                'options' => [
                    'placeholder' => 'Select Campaign',
                    'class' => 'form-control',
                    // 'id' => 'campaign_single',
                    // 'value' => '',
                ],
                'data' => [''],
```

**Comment by licanulla** [comment]
Still not a fix a this gives you an ungly empty element:
![image](https://user-images.githubusercontent.com/10324311/82726631-cda7ee00-9ce5-11ea-9101-da73cd8437bc.png)
and validation for it still passes.

**Comment by licanulla** [comment]
> not a issue of yii, but a issue of kartik-v/select2.
> A HTML5 `<select>` which is `required` MUST have at least one `<option>` Element.
> 
> > A select element with a required attribute and without a multiple attribute, and whose size is “1”, must have a child option element.
> 
> https://w3c.github.io/html-reference/select.html
> 
> i open a PR @kartik-v /select2

The below applies to
- latest yii2-widget-select2 (v2.1.7)
- latest yii (2.0.35)

The code produced by Select2 widget (without an empty option) appears to be valid:
`<select id="operation-customer_id" name="Operation[customer_id]" aria-required="true">`
according to https://validator.w3.org/ as there is NO required attribute on it and this [statement](https://github.com/kartik-v/yii2-widget-select2/issues/289#issuecomment-541415045) is not true:

![image](https://user-images.githubusercontent.com/10324311/82727373-65a7d680-9cea-11ea-95ec-ddaa5faca8a9.png)

With `required` attribute it is not:
![image](https://user-images.githubusercontent.com/10324311/82727393-86702c00-9cea-11ea-9874-6cc8b477b2a5.png)



The issue must be re-opened as the changes in yii.activeForm.js are breaking a correct validation:
https://github.com/kartik-v/yii2-widget-select2/issues/289#issuecomment-533504453

**Comment by samdark** [comment]
@licanulla any idea about fixing it properly?

**Comment by licanulla** [comment]
@samdark Not yet. 
I'm currently in a support mode of some of my old projects so will need time to dig into the code but hopefully someone who is actively using yii2 could catch up.

**Comment by buttflattery** [comment]
> Still not a fix a this gives you an ungly empty element:
> ![image](https://user-images.githubusercontent.com/10324311/82726631-cda7ee00-9ce5-11ea-9101-da73cd8437bc.png)
> and validation for it still passes.

@licanulla if the above was in context  to what i posted i can share the version numbers but it does not give you an ugly empty element when a placeholder is given and it does not allow you to pass the validation.

![image](https://user-images.githubusercontent.com/1536454/82735718-26ef3c00-9d3d-11ea-88bc-fd0c0b241c03.png)

Here is the complete code block i am using for one of those selects

```
<?php
        echo
        $form->field(
            $model,
            'campaign_from',
            [
                'template' => '{input}{error}',
            ]
        )->widget(
            Select2::class,
            [
                'options' => [
                    'placeholder' => 'Campaign From',
                    'class' => 'form-control',
                    'id' => 'campaign_from',
                ],
                'data' => [''],
                'theme' => Select2::THEME_BOOTSTRAP,
                'pluginOptions' => [
                    'minimumInputLength' => 3,
                    'allowClear' => true,
                    'ajax' => [
                        'url' => Url::to(['/user/campaign/campaign-listing']),
                        'method' => 'POST',
                        'dataType' => 'json',
                        'data' => new JsExpression(
                            'function(params){
                                let request_params= {
                                    q:params.term,
                                    page:params.page || 1
                                };
                                request_params[yii.getCsrfParam()]=yii.getCsrfToken();
                                return request_params;
                            }'
                        ),
                    ],
                ],
            ]
        )->label(false);
    ?>
```

Version Details
kartik-v/yii2-widget-select2        v2.1.7
yiisoft/yii2                                   v2.0.35 
OS                                              Windows10

**Comment by kartik-v** [comment]
I feel the change should be done to yii.activeform.js for the following conditions.

Validation for EMPTY OPTIONS for SELECT inputs must be restricted ONLY for the following conditions as specified by W3C validator:

- the select element has the `required` attribute set
- the select element does not have the `multiple` attribute set
- the select element has size is “1”

For all other conditions - the yii2 validation rules MUST BE allowed to run.

**Comment by samdark** [comment]
@kartik-v sounds about right. Are you into preparing these changes?

**Comment by kartik-v** [comment]
Will try to raise a PR

**Comment by kartik-v** [comment]
Submitted a PR #18065 to fix this.

**Comment by licanulla** [comment]
@samdark @kartik-v Thank you, guys!
