### ISSUE TITLE
Improve unclear upgrade warning for Query::select()

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#17397]
The warning that you get when upgrading to 2.0.20 is in my opinion very unclear:

> yii\db\Query::select() and addSelect() now normalize the columns when saving them to $this->select, so code that works directly with that property directly may need to be modified.

What does that mean? What is "normalize" in this regard (the word "normalize" is not even mentioned once on the respective [guide page](https://www.yiiframework.com/doc/guide/2.0/en/db-query-builder)). The docs for the `Query::normalizeSelect()` don't help either:

> Normalizes the SELECT columns passed to [[select()]] or [[addSelect()]].

Can we please get a more clear message here including examples etc.? The warning should also include bad examples that require action.

**Comment by s1lver** [comment]
for example:
```php
->select(['COUNT(test.field1) AS my_count, field2'])//BC
```
such a record will lead to the generation of incorrect SQL
You can rewrite this entry so:
```php
->select(['my_count' => 'COUNT(test.field1)', 'field2']) //you can write now
```

**Comment by samdark** [comment]
@s1lver the thing you've mentioned is now fixed.

**Comment by eggnukes** [comment]
There is still an issue with the update.

Code `->select(['rating' => 'AVG(rating)'])` generates following SQL `SELECT AVG(rating) AS AVG_rating AS rating`.

Setting the table name fixes the issue, but it should not be necessary for single table queries:
`->select(['rating' => 'AVG(table_name.rating)'])` generates working SQL `SELECT AVG(table_name.rating) AS rating`.

**Comment by samdark** [comment]
Does not look like it's alright/

**Comment by romec512** [comment]
I can't replay this problem. What am I doing wrong?

**Comment by terabytesoftw** [comment]
This has already been addressed by https://github.com/yiisoft/yii2/commit/f9a42c6703041dea051b30514028add0c957ded3, which expanded the Yii2 `2.0.20` upgrade note for `yii\db\Query::select()` and `addSelect()` with concrete before/after examples of the normalized `$select` format.

The current `UPGRADE.md` explains how values such as `select('*')` and `select('id, name')` are stored after normalization, which resolves the unclear upgrade warning reported here.

If further examples for complex SELECT expressions are needed, that should be handled as a separate documentation enhancement.

Closing this as resolved.
