### ISSUE TITLE
Add StatusUrlRuleInterface

### ISSUE THREAD

**Issue by brussens** [yiisoft/yii2#17411]
At the moment, all the logic with the rules that can be cached is in `UrlRule`. But when we implementing the class inherited from `BaseObject` and implementing `UrlRuleInterface`, the caching of this class occurs, which is not necessary in some cases. Of course, you can add methods and constants, but in the first case there is no `getCreateUrlStatus` hint method, and in the second case you have to make a copy of the constants into a new class, which is not very pleasant to do every time.
After thinking about it, I came to the conclusion that you can add an additional interface that will provide the `UrlRuleInterface` extensions with the necessary constants, which will allow you to remove crutches from `UrlManager`.

Approximately like this:
```php
interface StatusUrlRuleInterface extends UrlRuleInterface
{
    const CREATE_STATUS_SUCCESS = 0;
    const CREATE_STATUS_PARSING_ONLY = 1;
    const CREATE_STATUS_ROUTE_MISMATCH = 2;
    const CREATE_STATUS_PARAMS_MISMATCH = 4;
    
    public function getCreateUrlStatus();
}
```
Or better yet, a separate interface:
```php
interface StatusUrlRuleInterface
{
    const CREATE_STATUS_SUCCESS = 0;
    const CREATE_STATUS_PARSING_ONLY = 1;
    const CREATE_STATUS_ROUTE_MISMATCH = 2;
    const CREATE_STATUS_PARAMS_MISMATCH = 4;
    
    public function getCreateUrlStatus();
}
```

In the UrlManager itself, we'll be able to remove the incomprehensible crutch:
```php
protected function canBeCached(UrlRuleInterface $rule)
{
    return
        !($rule instanceof StatusUrlRuleInterface)
        || ($status = $rule->getCreateUrlStatus()) === null
        || $status === StatusUrlRuleInterface::CREATE_STATUS_SUCCESS
        || $status & StatusUrlRuleInterface::CREATE_STATUS_PARAMS_MISMATCH;
}
```
Implementation of rule classes will make it nicer:
```php
class MyUrlRule implements StatusUrlRuleInterface
{
    protected $status;

    public function parseRequest($manager, $request)
    {
        //some logic
    }

    public function createUrl($manager, $route, $params)
    {
        //some logic
    }

    public function getCreateUrlStatus()
    {
        return $this->status;
    }
}
```
Or better yet.

```php
class MyUrlRule implements UrlRuleInterface, StatusUrlRuleInterface
{
    use StatusUrlRuleTrait;

    public function parseRequest($manager, $request)
    {
        //some logic
    }

    public function createUrl($manager, $route, $params)
    {
        //some logic
    }
}
```
What do you think?

**Comment by rob006** [comment]
> In the UrlManager itself, we'll be able to remove the incomprehensible crutch:

I'm not sure what is the improvement here. You're replacing `!method_exists($rule, 'getCreateUrlStatus')` by `!($rule instanceof StatusUrlRuleInterface)` - not a big difference IMO. And it introduces minor BC break - every existing custom URL rule which implements `getCreateUrlStatus()` method, now needs to be adjusted to implement `StatusUrlRuleInterface` in order to keep current behavior. It is not worth the trouble IMO. 

To improve anything here we would need to add `getCreateUrlStatus()` to `UrlRuleInterface` and force integer as return type - this will remove or simplify some conditions. Since it will break BC it was planned for Yii 2.1, but things get complicated with Yii 3.0 and I'm not sure what is the status here.

**Comment by brussens** [comment]
> I'm not sure what is the improvement here. You're replacing !method_exists($rule, 'getCreateUrlStatus') by !($rule instanceof StatusUrlRuleInterface) - not a big difference IMO.

No, that's exactly the removal of the crutch, which is only done to make it work. It's funny that you're talking about backwards compatibility. It feels like some critical errors are only being fixed here, and when you start talking about some, even small improvements, they are perceived as bayonets. There are minor releases. Or is Yii not updated in minor? It's strange that I hear this from a member of Yii team.

> To improve anything here we would need to add getCreateUrlStatus() to UrlRuleInterface and force integer as return type - this will remove or simplify some conditions.

No, you're wrong. You do not need to add this to UrlRuleInterface. This method is not always needed because it adds a state to the UrlRule object.

**Comment by rob006** [comment]
> It feels like some critical errors are only being fixed here, and when you start talking about some, even small improvements, they are perceived as bayonets.

Yii 2 is in feature freeze mode. Don't expect enthusiastic reaction when you're proposing BC breaking change which does not fix anything. :]

> This method is not always needed because it adds a state to the UrlRule object.

A method cannot add state to object - how you implement it depends on you (you can always return the same result). This method is necessary to decide whether rule can be cached - requiring it allows to rely on types and reduce `instanceof` or `method_exists` checks and handling `null` as status.

But you're right about unnecessary state in `UrlRule` object - this is rather a hack to keep BC. Another thing to reconsider in next major release.

**Comment by samdark** [comment]
Won't be done in 2.0.
