### ISSUE TITLE
Call to undefined method yii\helpers\ArrayHelper::recursiveSort()

### ISSUE THREAD

**Issue by rasalom** [yiisoft/yii2#20004]
### What steps will reproduce the problem?
I save ActiveRecord model with jsonb postgres column type

### What is the expected result?
Save/update model without error

### Additional info

I corrected the error by copying functions "isIndexed", "recursiveSort" from file BaseArrayHelper to file ArrayHelper

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.48.1?
| PHP version      | 8.2 
| Operating system | Linux 4.15.0-213-generic Ubuntu

**Comment by bizley** [comment]
IIRC it was fixed with 2.0.49, could you check it?

**Comment by rasalom** [comment]
I will check, thanks

**Comment by rasalom** [comment]
After update to 2.0.49.3 error still exist:

    "name": "Exception",
    "message": "Call to undefined method yii\\helpers\\ArrayHelper::recursiveSort()",
    "code": 0,
    "type": "Error",
    "file": "private/vendor/yiisoft/yii2/db/BaseActiveRecord.php",
    "line": 1784,
    "stack-trace": [
        "#0 /private/vendor/yiisoft/yii2/db/BaseActiveRecord.php(653): yii\\db\\BaseActiveRecord->isValueDifferent()",
        "#1 private/vendor/yiisoft/yii2/db/BaseActiveRecord.php(806): yii\\db\\BaseActiveRecord->getDirtyAttributes()",
        "#2 private/vendor/yiisoft/yii2/db/ActiveRecord.php(680): yii\\db\\BaseActiveRecord->updateInternal()",
        "#3 private/vendor/yiisoft/yii2/db/BaseActiveRecord.php(690): yii\\db\\ActiveRecord->update()",
        "#4 private/controllers/DocumentsController.php(170): yii\\db\\BaseActiveRecord->save()",

**Comment by rob006** [comment]
Have you altered `ArrayHelper` or `BaseArrayHelper` in any way? This method is defined, so this error does not make any sense:

https://github.com/yiisoft/yii2/blob/01f39832275527bf9a8247df41a3d287e093a571/framework/helpers/BaseArrayHelper.php#L1026

**Comment by rasalom** [comment]
i have error in project
BaseArrayHelper was replaced by other definition
the error has been resolved
sorry
