### ISSUE TITLE
Enhance renderAjax method to control bundles from registering again

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii2#6838]
Related issue #4522. I will submit a PR with the following enhancements to the renderAjax method.

- Add a new parameter to renderAjax method named `unsetBundles`
- The `unsetBundles` can be a `bool` or `array`
     - if set to `false` no bundles will be unset.
     - if set to `true` all bundles will be unset.
     - if set to an array, the list of specified bundles will be unset. For example `['yii\web\YiiAsset', 'yii\web\JqueryAsset']`

This is important for rendering content via ajax and preventing injection of AssetBundle assets that are already rendered on the main page. However scripts/css registered via `registerJs` and `registerCss` will be embedded (and would need to be handled separately).

**Comment by llfm** [comment]
Prevent [js](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L262) files.
Prevent [css](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L285) files.

**Comment by kartik-v** [comment]
This enhancement is specific for AssetBundles only - not for individual JS/CSS files as I mentioned in the last part of my post.

**Comment by llfm** [comment]
>This is important for rendering content via ajax and preventing injection of AssetBundle assets that are already rendered on the main page.

AssetBundles are injected with the ajax always, true. But then Yii 2 filters it (see my last message).
With this you are just saving a few bytes - avoiding lines in the ajax response.

**Comment by kartik-v** [comment]
> But then Yii 2 filters it (see my last message).
It does not filter assets loaded by AssetBundle in renderAjax method - as tested and seen on the DOM.

Try to test an ActiveForm first loaded in a div on normal load. Then try to load the same form in the same div on click of a button via renderAjax.

You should see the following scripts getting loaded below the activeform again:

- yii\web\YiiAsset',
- yii\web\JqueryAsset
- yii\widgets\ActiveFormAsset
- yii\validators\ValidationAsset

**Comment by samdark** [comment]
@kartik-v it does: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L262

Please re-check it with 2.0.2 release code or master.

**Comment by kartik-v** [comment]
@samdark will check and test in case I do not have the latest version.

**Comment by kartik-v** [comment]
@samdark will check and test in case I do not have the latest version. 

Still, I would suggest doing it from PHP before the JS, would be a faster option.

**Comment by samdark** [comment]
Faster — maybe (I doubt it), more reliable — nope since JS could be loaded inside of other JS, by directly inserting `<script` tag etc.

**Comment by qiangxue** [comment]
You can try directly unsetting the unneeded bundles at the end of the ajax view.

**Comment by kartik-v** [comment]
@qiangxue - yes that would work but needs to be done for every view file rendered via ajax. Easier to set the `renderAjax` method with one additional param from the controller - especially if one wants to selectively unset bundles.

**Comment by qiangxue** [comment]
You may also do this: `Yii::$app->assetManager->bundles['xyz'] = false`. I don't quite like introducing `Controller::validateBundles()` as it seems irrelevant to a controller.

**Comment by kartik-v** [comment]
There are following approaches currently to do this from PHP:

- Manually unset bundles in the view or view layout. However when using a view layout, it seems using the render method works better than renderAjax due to some reason (the layout file has to be trimmed of the other content).
- Edit the assetManager as shown.
- Use the code I have in the PR and reuse it across the actions in a Controller.

Will check if there is anything better on this. 

The JS initScriptFilter is useful. But currently, the only issues with this are:
- You are rendering the script files and then unsetting from JS 
- You are depending on yii.js to be loaded (should be true for most scenarios - but what if not).

**Comment by kartik-v** [comment]
> I don't quite like introducing Controller::validateBundles() as it seems irrelevant to a controller.

@qiangxue this could be a static method that could be embedded in the `View` class as well.

**Comment by llfm** [comment]
>The JS initScriptFilter is useful. But currently, the only issues with this are:
>
> - You are rendering the script files and then unsetting from JS
> - You are depending on yii.js to be loaded (should be true for most scenarios - but what if not).

- You actually don't render the js files.
- Well, if you are returning html code and not only data, perhaps you are using pjax. Pjax has it's own way of handling [it](https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L735).

> You may actually be saving a lot of bytes depending on the size of the assets in the asset bundle.

@kartik-v This can be true. But maybe this is too specific and could add unnecessary ~complexity~.

Not sure about this, but in a scenario where AssetBundle add  'new files' to the 'layout' in response to an ajax response, you may need the `$depends` in order to it properly work (when a user goes directly to the page).

**Comment by klimov-paul** [comment]
Removing Asset Bundles after they have been registered does not sound as a correct way to solve the issue. It is better to prevent thier registration instead of doing double work: first register bundles, then unregister them.
The most simplest way to achieve this is set `AssetManager::bundles[$name] = false`.
This can be easy done inside the view file:
```php
<?php
/* @var $this yii\web\View */
if (Yii::$app->request->isAjax) {
    Yii::$app->assetManager->bundles['yii'] = false;
}
?>
...
```

**Comment by klimov-paul** [comment]
Another possible solution is introduction of pair of methods in the `yii\web\View`, which will disable/enable bundle registration for the view:
```php
<?php 
/* @var $this yii\web\View */
?>

some content

<?php $this->disableBundleRegistration() ?>
some code with widgets here
<?php $this->enableBundleRegistration() ?>

rest content
```

But I am usure it is better, then my previous comment.

**Comment by kartik-v** [comment]
@klimov-paul both approaches look good. 

I still feel whatever approach we take... the final enhancement is needed within the `Controller::renderAjax` method - for this to be beneficial. This is because the choice of how to render the view file with what AssetBundle for an ajax render... can be controlled centrally from the controller action - rather than calling such methods in each view file. This may help reduce lines of code probably as well as improve and ease maintenance of code significantly for those who wish to use this feature.

**Comment by klimov-paul** [comment]
I don't understand why it should be setup at controller action.
Asset Bundle belongs to the 'view' layer and should be handled there.
I don't think we can easy wrap this into some method, because the issue is not trivial.
While rendering some view via `renderAjax()` it is actually unknown which Asset Bundles should be registered and which are not.
If you render some area, which contains JUI widget, via AJAX, you want to disable 'jQuery' bundle to be loaded, but 'JUI' bundle should be registered. Still if you rerender it second time both those bundles shuld be excluded.
Such things are better to be handled at the client side, because only there you actually know which files are already loaded and which are not. At the server side there could not be elegant solution anyhow.

**Comment by kartik-v** [comment]
> I don't understand why it should be setup at controller action.

- The use case is when one wants to use the `renderAjax` method and it is part of the Controller method currently. 
- Currently there is no way I can control the AssetBundles registered via renderAjax
- The proposed approach to skip bundles is ONLY BY updating within the view  object

Where the above is tedious and difficult to maintain:
- a page which has several sections rendered using a single Controller Action using various AssetBundles but different view files... e.g. tabs, menu sections, master-detail sections etc.
- the above content will need to use a normal render on init
- will need to use renderAjax for refreshing via ajax

Most validation of such control is done within a single Controller Action and using renderAjax method to play with different view files.

**Comment by duynguyen0511** [comment]
@llfm  @samdark  https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L262

I am using Yii 2.0.4 and every default Yii asset bundle are loaded with the ajax form

![2015-06-24_1408](https://cloud.githubusercontent.com/assets/436950/8340290/d1280cb0-1a7a-11e5-9b47-45514243cd7a.png)

My only concern is double js scripts may cause conflicts which I havent seen yet. I would be nice that Yii 2 should not loaded those bundles if it is an ajax request because those bundles have been loaded by main page.

**Comment by papppeter** [comment]
Hi, 

our problem is some of clients are using yii2 developed site over proxy (mobile internet) which has a compression feature. So all the js, css files are automaticaly included into tha main dom (caching speeding up the sites.) The only problem that js, css cannot removed after ajax call. Site is broken after an ajax call.

do you have a method how should we use yii2?

**Comment by SilverFire** [comment]
Fixed in 2.0.7 by query filtering.
Please, update your framework version

**Comment by pappfer** [comment]
How is it fixed? I'm using the latest version (2.0.10-dev) and I still see all assets included again with renderAjax() which sometimes causes conflicts.

**Comment by papppeter** [comment]
This will be filtered out with a javascript on client side. So if your code is modified by a proxy (scripts included automatically into the html - not any more tags) than the javascript cannot filter it out any more.

our sollution was inserting a code into the main controller.

    public function init() {
        try{
            Yii::$app->response->headers->set('Cache-Control','no-transform');
        } catch(Exception $e) {}
    }

**Comment by pappfer** [comment]
@papppeter I think this is a different problem, I don't use proxy at all. The problem is that when I use renderAjax() the assets registered (for example jquery, bootstrap, etc) are going to get registered (inserted into the DOM) again, see the image uploaded by @duynguyen0511

**Comment by papppeter** [comment]
@pappfer ajax render sends the same amount of js as the normal renderer would. Just on client side there is a filter js function which filters the allready registered js out. On our case a proxy (mobile internet, etc) modified the output so yii2 js could not remove scripts and it was insereted into the DOM.

**Comment by Ariestattoo** [comment]
I am not sure what the status of this issue is, but I have a custom bootstrap implementation and I use a PJAX request to return a form which uses the Bootstrap  activeform implementation. Additionally, i use the asset compression tools built into the framework. When I run my site in Dev mode...the PJAX request returns the bootstrap css as being required even though it is already loaded by the main page, which isn't a huge amount of overhead. However when I run the site in production and my minified CSS file which contains all the CSS for the site is called on the PJAX request...that is a little expensive. It only does it once, but I'm wondering whether it should at all given it is already loaded. Additionally, the browser doesn't even cache the file because of the cache settings in the request. Is there a solution to this or a strategy to overcome the limitation?

**Comment by cebe** [comment]
@Ariestattoo sounds like your setup with compressed assets is not correct.

**Comment by Ariestattoo** [comment]
@cebe Anything jump out at you?    
     <?php
        /**
         * Configuration file for the "yii asset" console command.
         */
        
        // In the console environment, some path aliases may not exist. Please define these:
         Yii::setAlias('@webroot', __DIR__ . '/../web');
         Yii::setAlias('@web', '/');
        
        return [
            // Adjust command/callback for JavaScript files compressing:
            //'jsCompressor' => 'java -jar  /usr/local/bin g/yui-compressor/yui-compressor.jar --type js {from} -o {to}',
            'jsCompressor' => 'java -jar /home/steve/Apps/closure.jar --js {from} --js_output_file {to}',
            // Adjust command/callback for CSS files compressing:
            'cssCompressor' => 'java -jar /usr/share/yui-compressor/yui-compressor.jar --type css {from} -o {to}',
            // Whether to delete asset source after compression:
            'deleteSource' => false,
            // The list of asset bundles to compress:
            'bundles' => [
                 'frontend\assets\AppAsset',
                 'yii\web\YiiAsset',
                 'yii\web\JqueryAsset',
                 'frontend\assets\CroppieAsset',
                 'yii\bootstrap\BootstrapPluginAsset',
                 'yii\widgets\ActiveFormAsset',
                 'yii\validators\ValidationAsset',
                 'yii\bootstrap\BootstrapAsset',
                 'yii\widgets\PjaxAsset',
        
        
                 'frontend\assets\JquerySortableAsset',
                 'frontend\assets\ProfileFormAsset',
                 'frontend\assets\FontAwesomeAsset',
                 'frontend\assets\RotaryProgressAsset',
                 'frontend\assets\SearchAsset',
                 'frontend\assets\SlickAsset',
                 'frontend\assets\SliderAsset',
                 'frontend\assets\TouchPunchAsset',
                 'frontend\assets\UploadAsset',
                 'frontend\assets\WowAsset'
            ],
            // Asset bundle for compression output:
            'targets' => [
                'all' => [
                    'class' => 'yii\web\AssetBundle',
                    'basePath' => '@webroot',
                    'baseUrl' => '@cdn',
                    'js' => 'js/all-{hash}.js',
                    'css' => 'css/all-{hash}.css',
                ],
            ],
            // Asset manager configuration:
            'assetManager' => [
                'basePath' => '@webroot/assets',
                'baseUrl' => '@web/assets',
                'bundles' => [
                    'yii\bootstrap\BootstrapAsset' => [
                        'css' => [
                            'bootstrap.css' => '../../css/bootstrap.css'
                        ]
                    ]
                ]
            ],
        ];

**Comment by pappfer** [comment]
I'm sorry to comment again in a closed issue after a long time but this is still not working for me. I'm using the latest version of the framework.

I have a lot of scripts in my site and when I include a div using `renderAjax()` and it will register the same scripts again.
_In the screenshot you may see that Bootstrap hasn't been registered again and it is because I manually deregistered it using `Yii::$app->assetManager->bundles['yii\bootstrap\BootstrapAsset'] = false;`._

![assets-registered](https://cloud.githubusercontent.com/assets/738623/23822920/3065eebc-0657-11e7-9234-06f339794160.png)

Anyway, even if it would work for me, is it a good solution to remove these scripts from the client side? Does that mean that the browser downloads those scripts again and they just get removed from the DOM?

@papppeter Thank you, it makes sense now, however it wasn't the case for me. I tried it but it didn't work for me.
@kartik-v Are you happy with the provided solution? Actually I'm using your yii2-grid's ExpandRowColumn to include the content using renderAjax() and all scripts gets registered again.

**Comment by friek108** [comment]
I had a bit of a look into the code of `yii.js`, specifically the `initAssetFilters` function and seems `css` tags actually get removed from the dom. However, js work differently - they get included in the dom, however when the browser tries to 're-request' that js, it aborts and the javascript should never get reloaded. If you try this with a simple script with say, `alert("Hello World");` you'll see it only gets called once even though it is shown in the dom twice. 

Ideally, maybe yii.js should also remove duplicate `<script>` tags in the dom just to keep it clean (even though it doesn't appear to affect anything functionally).

**Comment by SilverFire** [comment]
> Ideally, maybe yii.js should also remove duplicate <script> tags in the dom just to keep it clean (even though I don't think it appears to affect anything functionally).

No, `script` tags contain the javascript that must be executed to make new content work. E.g. `$('#w1').gridView()`

**Comment by friek108** [comment]
I meant when there are 2 or more script tags that are the same (ie. one already exists in the dom like in the picture above, there are 2 x jquery.js and others). Are you saying they need to be duplicated to make the new content work? If that's true, makes sense..

**Comment by DaveFerger** [comment]
I have same problem, but ...

if i set
`assetManager->appendTimestamp = true`
and use
`controller->renderAjax()`
the jquery.js reload again

it think the initAssetFilters() dont recognized the timestamp variable

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.27 (Homebrew)
| Operating system | Mac OSX 10.11.6
