### ISSUE TITLE
Set default `HTMLPurifier` cache permissions to `0775`

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#9901]
While instantiating `HTMLPurifier` its 'Cache.SerializerPath' parameter is set to runie path, however 'Cache.SerializerPermissions' is not set, which means it stays default - '493'.

This causing a trouble running server, at which 'web server' (apache) user and developer are different system user and developer has no 'root' level access. `HTMLPurifier` produces directories `@runtime/HTML` and `@runtime/URI`, which can not be removed without 'root' level access.

I suggest we pass `0775` as 'Cache.SerializerPermissions' parameter, while instantiating `HTMLPurifier`.

**Comment by samdark** [comment]
Sounds OK.

**Comment by SilverFire** [comment]
I faced the problem some time ago, so the this is reasonable as for me

**Comment by klimov-paul** [comment]
Resolved by commit 8cbcbdded75e1658f87b4d76ef464690ddeca188

**Comment by gigo6000** [comment]
I still get this issue on yii2 2.0.7, the HTML dir is created without writing permission for the group.
